### ISSUE TITLE
 allocmd  generate worker failed

### ISSUE THREAD

**Issue by dancerinthedarkkk** [allora-network/allocmd#5]
root@DESKTOP-LSGF5S9:~/wsl/allora/allocmd# allocmd  generate worker --name zzh --topic 1  --env dev

      __      ___      ___        ______     _______        __
     /""\    |"  |    |"  |      /    " \   /"      \      /""\
    /    \   ||  |    ||  |     // ____  \ |:        |    /    \
   /' /\  \  |:  |    |:  |    /  /    ) :)|_____/   )   /' /\  \
  //  __'  \  \  |___  \  |___(: (____/ //  //      /   //  __'  \
 /   /  \\  \( \_|:  \( \_|:  \\        /  |:  __   \  /   /  \\  \
(___/    \___)\_______)\_______)\"_____/   |__|  \___)(___/    \___)

Welcome to the Allora CLI!
Allora CLI assists in the seamless creation and deployment of Allora worker nodes

This command will generate some files in the directory named 'zzh'.

Would you like to proceed? [Y/n]: Y

Proceeding with the creation of worker node directory...
local worker identity generated successfully.
Bootstraping 'zzh' directory...

All files bootstrapped successfully. ALLORA!!!
Traceback (most recent call last):
  File "/root/.local/bin/allocmd", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/root/.local/share/pipx/venvs/allocmd/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/allocmd/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/allocmd/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/allocmd/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/allocmd/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/allocmd/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/allocmd/lib/python3.12/site-packages/allocmd/cli.py", line 32, in worker
    blocklessNode(environment, env, BlocklessNodeType.worker.name, name, topic)
  File "/root/.local/share/pipx/venvs/allocmd/lib/python3.12/site-packages/allocmd/utilities/utils.py", line 301, in blocklessNode
    generateWorkerAccount(name, type)
  File "/root/.local/share/pipx/venvs/allocmd/lib/python3.12/site-packages/allocmd/utilities/utils.py", line 165, in generateWorkerAccount
    account_details = create_worker_account(worker_name, faucet_url, type)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/allocmd/lib/python3.12/site-packages/allocmd/utilities/utils.py", line 34, in create_worker_account
    subprocess.run(['make', 'install'],
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['make', 'install']' returned non-zero exit status 2.

**Comment by sandyliao80** [comment]
Me too
